### ISSUE TITLE
not compatible on edge runtimes (vercel/og)

### ISSUE THREAD

**Issue by juliusmarminge** [shuding/react-wrap-balancer#16]
trying to add this to my og images using `@vercel/og` but I am getting some errors regarding hook calls etc.

not sure if it's the edge runtime or the vercel og environment?

<img width="1011" alt="CleanShot 2022-12-31 at 12 11 20@2x" src="https://user-images.githubusercontent.com/51714798/210134616-7da52862-7881-4022-996b-f8f4a22a2ef3.png">

Code:

```ts
export default async (req: Request) => {
  const url = new URL(req.url);
  const inter = await getFont({
    family: "Inter",
    weights: [400, 700] as const,
  });

  const params = blogParams.decodeRequest(req);
  if (!params.success) return new Response("Invalid params", { status: 400 });
  const props = params.data.input;

  return new ImageResponse(
    (
      <div tw="...">
        <div tw="...">
          <h1 tw="... max-w-2xl">
            <Balancer>
              {props.title}
            </Balancer>
          </h1>
        </div>
        ...
      </div>
    ),
    ...
  );
};
```

**Comment by shuding** [comment]
Sorry that you run into this! For anyone who come to this, there’re a couple of things that I want to clarify.

First thing is Vercel’s OG image generation isn’t running the real React behind. It uses JSX but converts these elements and CSS into an image. These elements are not rendered by React in a browser.

Because of that, React APIs won’t work inside OG image generation (such as useState). So this library doesn’t work too.

And also, currently this library only works on the client (inside a browser), because it needs several browser APIs to get the element size as well as change the container width to relayout. All these can’t be done on the server, no matter if it’s Node.js or Edge runtime.

Lastly, there’s a way to support balanced wrapping in Vercel’s OG image generation, which is directly implement the CSS spec in the Satori library (rendering engine for Vercel’s OG).
