### ISSUE TITLE
native css variables for this

### ISSUE THREAD

**Issue by sakgoyal** [shuding/react-wrap-balancer#91]
what is the difference in using this package versus just applying the `text-wrap : pretty` property for text? 
using native css should be much more efficient wouldn't it?

**Comment by markpinero** [comment]
@sakgoyal This package is for cross-browser functionality. If you check Safari's compatibility, it only supports the latest version. And if you check the source code implementation, it checks if `text-wrap: balance` is supported, it defaults to that rather than the package code. So it does just what you're eluding to!
